on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
name: build
jobs:
  runhaskell:
    strategy:
      matrix:
        ghc: ['9.4.2']
    name: Build (cabal + GHC ${{ matrix.ghc }}) Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal','cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
            ${{ runner.os }}-
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
      - run: cabal build achille
      - run: cabal build achille-pandoc
      - run: cabal build achille-stache
      - run: cabal build docs
      - run: cabal build example
